### ISSUE TITLE
Error with Magento 2.3 and PHP 7

### ISSUE THREAD

**Issue by antony-perki** [omniful/omniful-magento2-plugin#1]
We get the following error when saving the product:

> Declaration of Omniful\Core\Model\Catalog\Product::updateProductsInventory(Omniful\Core\Model\Catalog\mixed $sku, int $qty, ?bool $status = NULL) must be compatible with Omniful\Core\Api\Catalog\ProductInterface::updateProductsInventory(Omniful\Core\Api\Catalog\mixed $sku, int $qty, ?bool $status = NULL) in /var/www/html/vendor/omniful/magento2-plugin/src/Core/Model/Catalog/Product.php on line 22

**Comment by abdelrhmankouta** [comment]
@antony-perki fixed with [commit](https://github.com/omniful/omniful-magento2-plugin/commit/59937eddacf9f625d6af1a8774a6dc143d991b21)
