### ISSUE TITLE
Error on the order view page for Magento 2.3

### ISSUE THREAD

**Issue by antony-perki** [omniful/omniful-magento2-plugin#3]
Here's the error

> PHP Fatal error:  Uncaught Error: Call to a member function displayShippingPriceIncludingTax() on null in /var/www/html/vendor/omniful/magento2-plugin/src/Core/view/adminhtml/templates/order/view/shipping/info.phtml:45

**Comment by abdelrhmankouta** [comment]
@antony-perki issue has been fixed with [commit](https://github.com/omniful/omniful-magento2-plugin/commit/66acb16814d526e84d0a2115f04fca19e83e5f8a)
